<?php
session_start();

if (!isset($_SESSION['student_logged_in']) || $_SESSION['student_logged_in'] !== true) {
    header("Location: student_login.php");
    exit;
}

// Assuming you have a database connection established elsewhere
// For example: include 'db_connection.php';

// You would typically retrieve the student's ID from the session
$student_id = $_SESSION['student_id']; // Make sure this session variable is set during login

// Function to fetch assignments for a specific student (you'll need to implement this)
function getStudentAssignments($student_id, $conn) {
    // Replace this with your actual database query
    $sql = "SELECT a.assignment_id, a.title, a.deadline, t.teacher_name
            FROM assignments a
            JOIN teachers t ON a.teacher_id = t.teacher_id
            WHERE a.student_id = ?";
    $stmt = $conn->prepare($sql);
    $stmt->bind_param("i", $student_id);
    $stmt->execute();
    $result = $stmt->get_result();
    $assignments = [];
    while ($row = $result->fetch_assoc()) {
        $assignments[] = $row;
    }
    $stmt->close();
    return $assignments;
}

// Function to fetch questions generated by teachers (you'll need to implement this)
function getTeacherGeneratedQuestions($conn) {
    // Replace this with your actual database query
    $sql = "SELECT q.question_id, q.question_text, t.teacher_name
            FROM questions q
            JOIN teachers t ON q.teacher_id = t.teacher_id";
    $result = $conn->query($sql);
    $questions = [];
    if ($result->num_rows > 0) {
        while ($row = $result->fetch_assoc()) {
            $questions[] = $row;
        }
    }
    return $questions;
}

// Fetch the student's assignments
// if (isset($conn)) {
//     $assignments = getStudentAssignments($student_id, $conn);
// } else {
//     $assignments = [];
//     echo "<p>Error: Database connection not established.</p>";
// }

// Fetch all teacher-generated questions
// if (isset($conn)) {
//     $questions = getTeacherGeneratedQuestions($conn);
// } else {
//     $questions = [];
//     echo "<p>Error: Database connection not established.</p>";
// }

?>

<!DOCTYPE html>
<html>
<head>
    <title>Student Dashboard</title>
</head>
<body>

    <ul>
        <li><a href="submit_assignment.php">Write Assignment</a></li>
        <li><a href="view_assignments.php">View My Assignments</a></li>
        <li><a href="view_questions.php">View Teacher Generated Questions</a></li>
    </ul>

    <a href="student_logout.php">Logout</a>
    </body>
</html>